### ISSUE TITLE
Using Button as a workflow manager

### ISSUE THREAD

**Issue by lomereiter** [jasonwhite/button#1]
Hi,

This looks like a promising project.

I wonder if it could be extended to compete with Luigi, Airflow and such, and how hard would it be. I guess, running `md5sum` would have to be optimized for >1GB files, e.g. by running it on progressively larger chunks of the file or something of this sort.

I'm honestly puzzled by the weird distinction between build systems and workflow managers since they both do the same, albeit with different file types. Some people even invent totally new languages like [BigDataScript](https://pcingola.github.io/BigDataScript/) to run their workflows. Maybe this 'very general', as you put it, project, could bring the two together?

**Comment by jasonwhite** [comment]
I wasn't actually aware of [Luigi](https://github.com/spotify/luigi), [Airflow](https://github.com/apache/incubator-airflow), or [Pinball](https://github.com/pinterest/pinball) until now. I need to look into these more closely, but from what I can tell, workflow managers are indeed basically build systems. Although, it looks like there are a few minor differences between build systems (please correct me if I'm wrong):
 * Tasks are usually more coarse-grained in a workflow manager, but there is no reason a build system can't have coarse-grained tasks either.
 * The inputs/outputs of tasks flow directly into one another and are not file-based. They don't keep track of intermediate files. Thus, the DAG is not bipartite.
 * Tasks are defined as code and can do other things besides run processes. In Button, you can only run processes. I'm not sure if this is a serious limitation in practice, as you could easily write a script to do anything you want.
 * There is more emphasis on running tasks in a distributed environment. Although other build systems, such as [Bazel](http://www.bazel.io/), can do this. Button doesn't do this (yet).
 * Workflow managers have a web interface. There is no reason a build system couldn't have this. In fact, I plan on implementing one for Button.

Looking at Pinball reminded me that I need to add retries and timeouts for tasks.

> I guess, running `md5sum` would have to be optimized for >1GB files, e.g. by running it on progressively larger chunks of the file or something of this sort.

I'm not sure what you mean by this. I assume you're talking about how Button considers a file to be "modified". Right now, it is somewhat of a heuristic. A file is only considered modified if the time stamp changed *and* the checksum changed. Thus, the checksum is only computed if the last modified time stamp changed.

**Comment by lomereiter** [comment]
To your second point: for coarse-grained tasks results usually are serialized to a file anyway. Even if not, it's easy to add extra file targets programmatically, taking, say, hashes of arguments as filenames, and `touch`ing them on successful completion.

Doing other things than running processes may seem useful, but in fact it's a lot cleaner to have one separate script per each task. AirFlow tutorial also uses exclusively `BashOperator` in the examples.

Distributed runs and web interface are nice to have, but for now should be just kept in mind when designing APIs. Among distributed task schedulers, I find Continuum's [`Distributed`](http://distributed.readthedocs.io/en/latest/foundations.html)  to be the operating in the most KISS way.

> I'm not sure what you mean by this

You got it right. I didn't realize it uses timestamps as well, thanks for clarifying.
